# ~/.aikey/hook.zsh — auto-generated by `aikey use`, do not hand-edit
# Version: 3
aikey() {
    case "$1" in
        activate|deactivate)
            local _output
            _output=$(command aikey "$@" --shell zsh)
            local _rc=$?
            if [ $_rc -eq 0 ]; then eval "$_output"; else return $_rc; fi
            ;;
        *) command aikey "$@" ;;
    esac
}

# `ak` is a binary symlink → aikey; this wrapper routes it through aikey() so
# `ak activate|deactivate` also gets eval-captured. Guarded — if the user has
# already defined `ak` (alias or function) for another tool, respect it.
#
# Why `function ak { ... }` (keyword form) not `ak() { ... }`: when the user
# has `alias ak=...` defined BEFORE this file is sourced, the parenthesis form
# triggers parse-time alias expansion on the function name (→ parse error).
# The `function` keyword form bypasses alias expansion on the name.
if ! (( ${+functions[ak]} )) && ! alias ak >/dev/null 2>&1; then
    function ak { aikey "$@"; }
fi

_aikey_precmd() {
    # Stage 4 cross-shell sync (2026-04-27):
    #   - `_AIKEY_EXPLICIT_ALIAS` is set by `aikey activate <alias>` and
    #     means "this shell is pinned, do NOT auto-sync from active.env".
    #     `AIKEY_ACTIVE_LABEL` is the legacy name kept during a 1-2 version
    #     grace window for older `aikey activate` outputs still in flight.
    #   - `AIKEY_AUTO_REFRESH=off` is the user kill-switch.
    #   - When neither pin nor kill-switch is set, do a cheap seq diff.
    #     active.env now embeds `export AIKEY_ACTIVE_SEQ="N"` near the top;
    #     if it matches the in-shell value, skip the source — that is the
    #     hot path on every prompt and must stay <1ms.
    #   - When the file is missing the SEQ line (older CLI wrote it) we
    #     fall back to unconditional source for correctness.
    [[ "$AIKEY_AUTO_REFRESH" == "off" ]] && { _aikey_hook_check_once; return; }
    [[ -n "$_AIKEY_EXPLICIT_ALIAS" || -n "$AIKEY_ACTIVE_LABEL" ]] && { _aikey_hook_check_once; return; }
    [[ -f ~/.aikey/active.env ]] || { _aikey_hook_check_once; return; }
    local on_disk_seq
    on_disk_seq=$(grep -m1 -oE 'AIKEY_ACTIVE_SEQ="[0-9]+"' ~/.aikey/active.env 2>/dev/null \
                  | grep -oE '[0-9]+')
    if [[ -n "$on_disk_seq" ]]; then
        if [[ "$on_disk_seq" != "${AIKEY_ACTIVE_SEQ:-0}" ]]; then
            source ~/.aikey/active.env
            [[ -n "$AIKEY_REFRESH_NOTIFY" ]] && \
                printf '\033[90m[aikey] active key refreshed (seq=%s)\033[0m\n' "$AIKEY_ACTIVE_SEQ" >&2
        fi
    else
        # Fallback for active.env produced by pre-Stage-1 CLI (no SEQ line).
        source ~/.aikey/active.env
    fi
    _aikey_hook_check_once
}

# One-shot drift detector: compare the `# Hook-Template-Hash:` header of
# ~/.aikey/hook.zsh against the hash embedded in the `aikey` binary
# (`aikey _hook-hash zsh`). A mismatch means the binary was upgraded but
# the on-disk hook wasn't regenerated (the 2026-04-22 root cause — user
# sees old wrapper behaviour despite a newer binary being installed).
#
# Why once-per-shell: the comparison involves a file read + one binary
# invocation; doing it on every prompt would be wasteful. The
# `_AIKEY_HOOK_CHECKED` flag scopes it to first prompt, then silence.
_aikey_hook_check_once() {
    [ -n "$_AIKEY_HOOK_CHECKED" ] && return
    _AIKEY_HOOK_CHECKED=1
    local file_hash bin_hash
    file_hash=$(grep -m1 -oE 'Hook-Template-Hash: [a-f0-9]+' ~/.aikey/hook.zsh 2>/dev/null | cut -d' ' -f2)
    bin_hash=$(command aikey _hook-hash zsh 2>/dev/null)
    # If either side is missing (pre-hash binary, stripped hook file),
    # stay silent — the drift detector is strictly best-effort.
    [[ -z "$file_hash" || -z "$bin_hash" ]] && return

    # M1 (2026-04-22): in-memory vs on-disk drift → auto-reload (plan C).
    #
    # `$_AIKEY_HOOK_LOADED_HASH` is set by the hook file itself at source
    # time. If it differs from the current on-disk hash, the user has
    # regenerated the hook file AFTER this shell sourced it — wrapper
    # defs in memory are stale.
    #
    # We auto-reload in-place (matches zsh's norm — direnv/pyenv do this)
    # and print a single dim line so the event is visible without being
    # noisy. Re-check AFTER source: if `source` somehow didn't take
    # effect (interrupted file write, permission issue, concurrent edit
    # racing), fall back to warning the user manually.
    #
    # Checked BEFORE the on-disk-vs-binary check: fixing in-shell drift
    # is usually what the user actually wants right now.
    if [[ -n "$_AIKEY_HOOK_LOADED_HASH" && "$_AIKEY_HOOK_LOADED_HASH" != "$file_hash" ]]; then
        local _old_hash="$_AIKEY_HOOK_LOADED_HASH"
        source ~/.aikey/hook.zsh 2>/dev/null
        # After a successful source, `_AIKEY_HOOK_LOADED_HASH` was reassigned
        # by the top-of-file assignment. Verify the reload actually took.
        if [[ "$_AIKEY_HOOK_LOADED_HASH" == "$file_hash" ]]; then
            printf '\033[90m[aikey] hook reloaded in this shell (%s → %s)\033[0m\n' "$_old_hash" "$file_hash" >&2
            # Reset the one-shot guard so if another drift happens later in
            # this shell (e.g. user runs `aikey use` again), it's detected
            # on the next prompt. Normal stable-state still costs only one
            # check per shell.
            _AIKEY_HOOK_CHECKED=
        else
            printf '\033[33m[aikey] hook drift detected but auto-reload failed.\n    run manually: source ~/.aikey/hook.zsh\033[0m\n' >&2
        fi
        return
    fi

    if [[ "$file_hash" != "$bin_hash" ]]; then
        printf '\033[33m[aikey] hook.zsh is outdated (file=%s, binary=%s).\n    run: aikey use   # regenerates ~/.aikey/hook.zsh, then re-source\n\033[0m' "$file_hash" "$bin_hash" >&2
    fi
}

_aikey_preexec() {
    [[ -z "$AIKEY_ACTIVE_KEYS" ]] && return
    local cmd="${1%% *}" prov
    case "$cmd" in
        claude) prov=anthropic ;;
        codex)  prov=openai ;;
        kimi)   prov=kimi ;;
        *) return ;;
    esac
    local id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    [[ -n "$id" ]] && printf '\033[90m[aikey] %s → %s\033[0m\n' "$cmd" "$id"
}

# Dedupe-safe registration — re-sourcing this file is harmless.
(( ${precmd_functions[(I)_aikey_precmd]} )) || precmd_functions+=(_aikey_precmd)
(( ${preexec_functions[(I)_aikey_preexec]} )) || preexec_functions+=(_aikey_preexec)

# ── Wrapper preflight (claude / codex) ────────────────────────────────────
#
# Runs `aikey test <alias>` before the real claude/codex binary to catch
# "proxy down / key expired / wrong env" cases instead of letting the user
# hit them as an opaque CLI error 30 seconds in. On failure, prompts the
# user interactively — default answer is "no" so typos don't silently fall
# through into a broken session.
#
# Escape hatch: `AIKEY_PREFLIGHT=off` (any shell) skips the probe entirely.
#
# Password handling: `aikey test` calls `prompt_vault_password` which
# consults the session cache first. If the user ran `aikey activate <alias>`
# earlier in this shell (or keychain backend is enabled), cache hits and no
# prompt appears. We redirect stdin from /dev/null so a cache-miss turns
# into a graceful non-zero exit rather than a blocking password prompt —
# wrapper then treats that like any other preflight failure (warn + ask).
_aikey_preflight() {
    [[ "$AIKEY_PREFLIGHT" == "off" ]] && return 0
    # No active binding in this shell — can't tell what to probe. Emit one
    # advisory line so first-time users see the missing step instead of a
    # raw `claude` error 30s in. Silent no-op would be defensible but the
    # hint costs one line and saves a support round-trip.
    if [[ -z "$AIKEY_ACTIVE_KEYS" ]]; then
        printf '\033[90m[aikey] no active binding — run `aikey use <alias>` first (preflight skipped)\033[0m\n' >&2
        return 0
    fi
    local prov="$1"
    local id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    # No active binding for this provider — don't block; let the real CLI
    # surface its own "no credentials" error (more specific than ours).
    [[ -z "$id" ]] && return 0
    # Let stderr through so the user sees the Ping/API/Chat table (that's
    # real feedback, not noise) — a silent 1-2s pause before claude looks
    # like the shell hanging. Stdin still redirected from /dev/null so any
    # interactive prompt from aikey test (shouldn't happen post plan D,
    # belt-and-suspenders against a regression) can't block the wrapper.
    command aikey test "$id" </dev/null
    local rc=$?
    [[ $rc -eq 0 ]] && return 0
    # Exit codes from `aikey test` (see main.rs Commands::Test):
    #   1 = Ping(PROXY) fail · 2 = API fail · 3 = alias not found
    #   5 = proxy not running · other = unexpected
    local reason
    case "$rc" in
        1) reason="proxy can't reach upstream" ;;
        2) reason="API rejected the key" ;;
        3) reason="alias not found" ;;
        5) reason="aikey-proxy not running" ;;
        *) reason="exit=$rc" ;;
    esac
    printf '\033[33m[aikey] preflight failed for %s (%s): %s. Continue anyway? [y/N] \033[0m' "$prov" "$id" "$reason"
    local reply
    read -r reply
    case "$reply" in
        y|Y|yes|YES) return 0 ;;
        *) printf '\033[90m[aikey] aborted — run: aikey test %s\033[0m\n' "$id"; return 1 ;;
    esac
}

# Clear-before-handoff for terminals with broken alt-screen (2026-04-27).
#
# Symptom: when preflight runs `aikey test`, several lines hit the main
# screen. The wrapped command (claude / codex) then enters its own TUI
# via `\x1b[?1049h`. On terminals that DON'T implement alt-screen as a
# separate buffer (older macOS Terminal.app, some VTE forks) the
# preflight output gets "snapshotted" into the alt-screen entry and
# ghosts under the wrapped TUI's own rendering — users report seeing
# multiple stacked window snapshots.
#
# Heuristic mirrors `terminal_supports_alt_screen` in
# aikey-cli/src/commands_watch.rs. Modern emulators (iTerm.app,
# WezTerm, Kitty, vscode, Hyper, GNOME Terminal, modern Terminal.app)
# handle alt-screen properly → keep preflight output visible. Known-
# broken terminals → clear before handoff so the wrapped TUI starts
# on a blank canvas.
#
# Override knobs:
#   AIKEY_PREFLIGHT_NO_CLEAR=1     → never clear
#   AIKEY_PREFLIGHT_FORCE_CLEAR=1  → always clear (for false negatives)
_aikey_clear_before_tui_handoff() {
    [[ "$AIKEY_PREFLIGHT_NO_CLEAR" == "1" ]] && return 0
    if [[ "$AIKEY_PREFLIGHT_FORCE_CLEAR" == "1" ]]; then
        printf '\033[H\033[2J' >&2
        return 0
    fi
    # Non-interactive (stderr not a TTY) — no human to confuse.
    [[ ! -t 2 ]] && return 0
    # Multiplexer pass-through: tmux / screen handle alt-screen safely.
    [[ -n "$TMUX" ]] && return 0
    [[ -n "$STY"  ]] && return 0
    case "$TERM" in
        screen*|tmux*) return 0 ;;
        dumb|unknown|"") printf '\033[H\033[2J' >&2; return 0 ;;
    esac
    # Old macOS Terminal.app (build < 433) is the canonical broken case.
    if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]]; then
        local build="${TERM_PROGRAM_VERSION:-0}"
        # Strip any decoration (rare, but defensive: parse only digits).
        build="${build//[^0-9]/}"
        [[ -z "$build" ]] && build=0
        if (( build < 433 )); then
            printf '\033[H\033[2J' >&2
        fi
        return 0
    fi
    # Modern terminals: trust them, leave preflight output visible.
    return 0
}

# Wrap claude + codex. Guarded so the user's own function/alias (if any)
# wins — respects the same convention as the `ak` wrapper above.
if ! (( ${+functions[claude]} )) && ! alias claude >/dev/null 2>&1; then
    function claude {
        _aikey_preflight anthropic || return $?
        _aikey_clear_before_tui_handoff
        command claude "$@"
    }
fi
if ! (( ${+functions[codex]} )) && ! alias codex >/dev/null 2>&1; then
    function codex {
        _aikey_preflight openai || return $?
        _aikey_clear_before_tui_handoff
        command codex "$@"
    }
fi
