# ~/.aikey/hook.bash — auto-generated by `aikey use`, do not hand-edit
# Version: 3
aikey() {
    case "$1" in
        activate|deactivate)
            local _output
            _output=$(command aikey "$@" --shell bash)
            local _rc=$?
            if [ $_rc -eq 0 ]; then eval "$_output"; else return $_rc; fi
            ;;
        *) command aikey "$@" ;;
    esac
}

# Guarded: respect a pre-existing ak alias/function (e.g. user's kubectl shortcut).
if ! type ak >/dev/null 2>&1; then
    ak() { aikey "$@"; }
fi

_aikey_precmd_bash() {
    [ -n "$AIKEY_ACTIVE_LABEL" ] && return
    [ -f ~/.aikey/active.env ] && source ~/.aikey/active.env
    _aikey_hook_check_once
}

# Drift detector — see hook.zsh for full rationale (both layers).
_aikey_hook_check_once() {
    [ -n "$_AIKEY_HOOK_CHECKED" ] && return
    _AIKEY_HOOK_CHECKED=1
    local file_hash bin_hash
    file_hash=$(grep -m1 -oE 'Hook-Template-Hash: [a-f0-9]+' ~/.aikey/hook.bash 2>/dev/null | cut -d' ' -f2)
    bin_hash=$(command aikey _hook-hash bash 2>/dev/null)
    [ -z "$file_hash" ] || [ -z "$bin_hash" ] && return

    # M1 (2026-04-22): in-memory vs on-disk drift → auto-reload (plan C).
    # See hook.zsh comment for full rationale.
    if [ -n "$_AIKEY_HOOK_LOADED_HASH" ] && [ "$_AIKEY_HOOK_LOADED_HASH" != "$file_hash" ]; then
        local _old_hash="$_AIKEY_HOOK_LOADED_HASH"
        source ~/.aikey/hook.bash 2>/dev/null
        if [ "$_AIKEY_HOOK_LOADED_HASH" = "$file_hash" ]; then
            printf '\033[90m[aikey] hook reloaded in this shell (%s → %s)\033[0m\n' "$_old_hash" "$file_hash" >&2
            _AIKEY_HOOK_CHECKED=
        else
            printf '\033[33m[aikey] hook drift detected but auto-reload failed.\n    run manually: source ~/.aikey/hook.bash\033[0m\n' >&2
        fi
        return
    fi

    if [ "$file_hash" != "$bin_hash" ]; then
        printf '\033[33m[aikey] hook.bash is outdated (file=%s, binary=%s).\n    run: aikey use   # regenerates ~/.aikey/hook.bash, then re-source\n\033[0m' "$file_hash" "$bin_hash" >&2
    fi
}

_aikey_preexec_bash() {
    [ -z "$AIKEY_ACTIVE_KEYS" ] && return
    local cmd="${BASH_COMMAND%% *}" prov
    case "$cmd" in
        claude) prov=anthropic ;;
        codex)  prov=openai ;;
        kimi)   prov=kimi ;;
        *) return ;;
    esac
    local id
    id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    [ -n "$id" ] && printf '\033[90m[aikey] %s → %s\033[0m\n' "$cmd" "$id"
}

# Dedupe-safe PROMPT_COMMAND registration. Append-with-check preserves hooks
# from direnv / pyenv / atuin that may have registered first.
case ";$PROMPT_COMMAND;" in
    *\;_aikey_precmd_bash\;*) ;;
    *) PROMPT_COMMAND="_aikey_precmd_bash${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
esac
# bash has no native preexec — fall back to the DEBUG trap. But DEBUG can hold
# only one handler at a time, so unconditionally setting it would clobber any
# trap the user (or tools like bash-preexec) already installed. Defer if one
# exists; we lose the per-command label echo but preserve user plumbing. Users
# who want the label can integrate via `bash-preexec.sh`'s `preexec_functions`.
if [ -z "$(trap -p DEBUG 2>/dev/null)" ]; then
    trap '_aikey_preexec_bash' DEBUG
fi

# ── Wrapper preflight (claude / codex) ────────────────────────────────────
#
# See hook.zsh for the full rationale. Same contract here:
#   - AIKEY_PREFLIGHT=off disables the probe.
#   - stdin </dev/null so password prompts turn into graceful non-zero exits
#     (session-cache hits stay silent, cache misses become a preflight fail
#     rather than a hanging prompt).
#   - On non-zero exit, warn + prompt, default "no".
_aikey_preflight() {
    [ "$AIKEY_PREFLIGHT" = "off" ] && return 0
    # No active binding in this shell — emit an advisory line instead of
    # silently passing through. See hook.zsh for the full rationale.
    if [ -z "$AIKEY_ACTIVE_KEYS" ]; then
        printf '\033[90m[aikey] no active binding — run `aikey use <alias>` first (preflight skipped)\033[0m\n' >&2
        return 0
    fi
    local prov="$1"
    local id
    id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    [ -z "$id" ] && return 0
    # Let stderr through — see hook.zsh for rationale. Silent success
    # looked like a hang to users, so the full Ping/API/Chat table now
    # shows up every time.
    command aikey test "$id" </dev/null
    local rc=$?
    [ $rc -eq 0 ] && return 0
    local reason
    case "$rc" in
        1) reason="proxy can't reach upstream" ;;
        2) reason="API rejected the key" ;;
        3) reason="alias not found" ;;
        5) reason="aikey-proxy not running" ;;
        *) reason="exit=$rc" ;;
    esac
    printf '\033[33m[aikey] preflight failed for %s (%s): %s. Continue anyway? [y/N] \033[0m' "$prov" "$id" "$reason"
    local reply
    read -r reply
    case "$reply" in
        y|Y|yes|YES) return 0 ;;
        *) printf '\033[90m[aikey] aborted — run: aikey test %s\033[0m\n' "$id"; return 1 ;;
    esac
}

# Wrap claude + codex. Guarded: only install if the user doesn't already
# have a function/alias by the same name. `type` checks functions, aliases,
# builtins, and PATH — we only want to skip when the first three match (PATH
# is the real binary we'll call via `command`). Shell grammar limitation:
# there's no clean one-liner to split that, so use `declare -F` + alias.
if ! declare -F claude >/dev/null 2>&1 && ! alias claude >/dev/null 2>&1; then
    claude() { _aikey_preflight anthropic || return $?; command claude "$@"; }
fi
if ! declare -F codex >/dev/null 2>&1 && ! alias codex >/dev/null 2>&1; then
    codex() { _aikey_preflight openai || return $?; command codex "$@"; }
fi
