# ~/.aikey/hook.bash — auto-generated by `aikey use`, do not hand-edit
# Version: 3
aikey() {
    case "$1" in
        activate|deactivate)
            local _output
            _output=$(command aikey "$@" --shell bash)
            local _rc=$?
            if [ $_rc -eq 0 ]; then eval "$_output"; else return $_rc; fi
            ;;
        *) command aikey "$@" ;;
    esac
}

# Guarded: respect a pre-existing ak alias/function (e.g. user's kubectl shortcut).
if ! type ak >/dev/null 2>&1; then
    ak() { aikey "$@"; }
fi

_aikey_precmd_bash() {
    [ -n "$AIKEY_ACTIVE_LABEL" ] && return
    [ -f ~/.aikey/active.env ] && source ~/.aikey/active.env
}

_aikey_preexec_bash() {
    [ -z "$AIKEY_ACTIVE_KEYS" ] && return
    local cmd="${BASH_COMMAND%% *}" prov
    case "$cmd" in
        claude) prov=anthropic ;;
        codex)  prov=openai ;;
        kimi)   prov=kimi ;;
        *) return ;;
    esac
    local id
    id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    [ -n "$id" ] && printf '\033[90m[aikey] %s → %s\033[0m\n' "$cmd" "$id"
}

# Dedupe-safe PROMPT_COMMAND registration. Append-with-check preserves hooks
# from direnv / pyenv / atuin that may have registered first.
case ";$PROMPT_COMMAND;" in
    *\;_aikey_precmd_bash\;*) ;;
    *) PROMPT_COMMAND="_aikey_precmd_bash${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
esac
# bash has no native preexec — fall back to the DEBUG trap. But DEBUG can hold
# only one handler at a time, so unconditionally setting it would clobber any
# trap the user (or tools like bash-preexec) already installed. Defer if one
# exists; we lose the per-command label echo but preserve user plumbing. Users
# who want the label can integrate via `bash-preexec.sh`'s `preexec_functions`.
if [ -z "$(trap -p DEBUG 2>/dev/null)" ]; then
    trap '_aikey_preexec_bash' DEBUG
fi
