# ~/.aikey/hook.zsh — auto-generated by `aikey use`, do not hand-edit
# Version: 4
aikey() {
    case "$1" in
        activate|deactivate)
            local _output
            _output=$(command aikey "$@" --shell zsh)
            local _rc=$?
            if [ $_rc -eq 0 ]; then eval "$_output"; else return $_rc; fi
            ;;
        *) command aikey "$@" ;;
    esac
}

# `ak` is a binary symlink → aikey; this wrapper routes it through aikey() so
# `ak activate|deactivate` also gets eval-captured. Guarded — if the user has
# already defined `ak` (alias or function) for another tool, respect it.
#
# Why `function ak { ... }` (keyword form) not `ak() { ... }`: when the user
# has `alias ak=...` defined BEFORE this file is sourced, the parenthesis form
# triggers parse-time alias expansion on the function name (→ parse error).
# The `function` keyword form bypasses alias expansion on the name.
if ! (( ${+functions[ak]} )) && ! alias ak >/dev/null 2>&1; then
    function ak { aikey "$@"; }
fi

_aikey_precmd() {
    # Stage 4 cross-shell sync (2026-04-27):
    #   - `_AIKEY_EXPLICIT_ALIAS` is set by `aikey activate <alias>` and
    #     means "this shell is pinned, do NOT auto-sync from active.env".
    #     `AIKEY_ACTIVE_LABEL` is the legacy name kept during a 1-2 version
    #     grace window for older `aikey activate` outputs still in flight.
    #   - `AIKEY_AUTO_REFRESH=off` is the user kill-switch.
    #   - When neither pin nor kill-switch is set, do a cheap seq diff.
    #     active.env now embeds `export AIKEY_ACTIVE_SEQ="N"` near the top;
    #     if it matches the in-shell value, skip the source — that is the
    #     hot path on every prompt and must stay <1ms.
    #   - When the file is missing the SEQ line (older CLI wrote it) we
    #     fall back to unconditional source for correctness.
    [[ "$AIKEY_AUTO_REFRESH" == "off" ]] && { _aikey_hook_check_once; return; }
    [[ -n "$_AIKEY_EXPLICIT_ALIAS" || -n "$AIKEY_ACTIVE_LABEL" ]] && { _aikey_hook_check_once; return; }
    [[ -f ~/.aikey/active.env ]] || { _aikey_hook_check_once; return; }
    local on_disk_seq
    on_disk_seq=$(grep -m1 -oE 'AIKEY_ACTIVE_SEQ="[0-9]+"' ~/.aikey/active.env 2>/dev/null \
                  | grep -oE '[0-9]+')
    if [[ -n "$on_disk_seq" ]]; then
        if [[ "$on_disk_seq" != "${AIKEY_ACTIVE_SEQ:-0}" ]]; then
            source ~/.aikey/active.env
            [[ -n "$AIKEY_REFRESH_NOTIFY" ]] && \
                printf '\033[90m[aikey] active key refreshed (seq=%s)\033[0m\n' "$AIKEY_ACTIVE_SEQ" >&2
        fi
    else
        # Fallback for active.env produced by pre-Stage-1 CLI (no SEQ line).
        source ~/.aikey/active.env
    fi
    _aikey_hook_check_once
}

# Two-layer drift detector. Why split: the previous one-shot design ran
# both checks on the first prompt and never again, missing the common case
# "user updated binary+hook AFTER this shell was opened" — observed
# 2026-04-28: `make restart-trial1` regenerated hook to hash Y, but every
# subsequent prompt skipped the check because `_AIKEY_HOOK_CHECKED=1` was
# already set from the no-drift first run. Wrappers in memory stayed at
# the pre-update version forever.
#
# Layer 1 (every prompt, ~1ms): grep the disk hook header and compare
# against `$_AIKEY_HOOK_LOADED_HASH` (set by the hook file itself at
# source time). Cheap enough to run on each prompt — first-line grep on
# a small file is sub-millisecond on a hot disk cache. Catches the
# common case (in-memory wrappers stale relative to disk) reliably.
#
# Layer 2 (once per shell): spawn `aikey _hook-hash zsh` to compare disk
# hash vs binary's embedded hash. Catches the rarer case (binary upgraded
# but hook file not regenerated). One-shot guard via `_AIKEY_HOOK_CHECKED`
# kept here because binary spawns aren't free (~20ms).
_aikey_hook_check_once() {
    # ── Layer 1 (every prompt) ──────────────────────────────────────────
    # Auto-reload when the disk file has changed since this shell sourced it.
    if [ -n "$_AIKEY_HOOK_LOADED_HASH" ]; then
        local _disk_hash
        _disk_hash=$(grep -m1 -oE 'Hook-Template-Hash: [a-f0-9]+' ~/.aikey/hook.zsh 2>/dev/null | cut -d' ' -f2)
        if [[ -n "$_disk_hash" && "$_disk_hash" != "$_AIKEY_HOOK_LOADED_HASH" ]]; then
            local _old_hash="$_AIKEY_HOOK_LOADED_HASH"
            source ~/.aikey/hook.zsh 2>/dev/null
            # After source, `_AIKEY_HOOK_LOADED_HASH` was reassigned by
            # the top-of-file line. Verify the reload actually took.
            if [[ "$_AIKEY_HOOK_LOADED_HASH" == "$_disk_hash" ]]; then
                printf '\033[90m[aikey] hook reloaded in this shell (%s → %s)\033[0m\n' "$_old_hash" "$_disk_hash" >&2
                # Re-arm the layer-2 guard so the binary-vs-disk check
                # runs once against the new hook content too.
                _AIKEY_HOOK_CHECKED=
            else
                printf '\033[33m[aikey] hook drift detected but auto-reload failed.\n    run manually: source ~/.aikey/hook.zsh\033[0m\n' >&2
            fi
            return
        fi
    fi

    # ── Layer 2 (once per shell) ────────────────────────────────────────
    # Binary-vs-disk hash compare. Skipped on subsequent prompts via flag.
    [ -n "$_AIKEY_HOOK_CHECKED" ] && return
    _AIKEY_HOOK_CHECKED=1
    local file_hash bin_hash
    file_hash=$(grep -m1 -oE 'Hook-Template-Hash: [a-f0-9]+' ~/.aikey/hook.zsh 2>/dev/null | cut -d' ' -f2)
    bin_hash=$(command aikey _hook-hash zsh 2>/dev/null)
    # If either side is missing (pre-hash binary, stripped hook file),
    # stay silent — the drift detector is strictly best-effort.
    [[ -z "$file_hash" || -z "$bin_hash" ]] && return
    if [[ "$file_hash" != "$bin_hash" ]]; then
        printf '\033[33m[aikey] hook.zsh is outdated (file=%s, binary=%s).\n    run: aikey use   # regenerates ~/.aikey/hook.zsh, then re-source\n\033[0m' "$file_hash" "$bin_hash" >&2
    fi
}

_aikey_preexec() {
    [[ -z "$AIKEY_ACTIVE_KEYS" ]] && return
    local cmd="${1%% *}" prov
    case "$cmd" in
        claude) prov=anthropic ;;
        codex)  prov=openai ;;
        kimi)   prov=kimi ;;
        *) return ;;
    esac
    local id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    [[ -n "$id" ]] && printf '\033[90m[aikey] %s → %s\033[0m\n' "$cmd" "$id"
}

# Dedupe-safe registration — re-sourcing this file is harmless.
(( ${precmd_functions[(I)_aikey_precmd]} )) || precmd_functions+=(_aikey_precmd)
(( ${preexec_functions[(I)_aikey_preexec]} )) || preexec_functions+=(_aikey_preexec)

# ── Wrapper preflight (claude / codex) ────────────────────────────────────
#
# Runs `aikey test <alias>` before the real claude/codex binary to catch
# "proxy down / key expired / wrong env" cases instead of letting the user
# hit them as an opaque CLI error 30 seconds in. On failure, prompts the
# user interactively — default answer is "no" so typos don't silently fall
# through into a broken session.
#
# Escape hatch: `AIKEY_PREFLIGHT=off` (any shell) skips the probe entirely.
#
# Password handling: `aikey test` calls `prompt_vault_password` which
# consults the session cache first. If the user ran `aikey activate <alias>`
# earlier in this shell (or keychain backend is enabled), cache hits and no
# prompt appears. We redirect stdin from /dev/null so a cache-miss turns
# into a graceful non-zero exit rather than a blocking password prompt —
# wrapper then treats that like any other preflight failure (warn + ask).
_aikey_preflight() {
    [[ "$AIKEY_PREFLIGHT" == "off" ]] && return 0
    # No active binding in this shell — can't tell what to probe. Emit one
    # advisory line so first-time users see the missing step instead of a
    # raw `claude` error 30s in. Silent no-op would be defensible but the
    # hint costs one line and saves a support round-trip.
    if [[ -z "$AIKEY_ACTIVE_KEYS" ]]; then
        printf '\033[90m[aikey] no active binding — run `aikey use <alias>` first (preflight skipped)\033[0m\n' >&2
        return 0
    fi
    local prov="$1"
    local id=$(echo "$AIKEY_ACTIVE_KEYS" | tr ',' '\n' | grep "^${prov}=" | cut -d= -f2-)
    # No active binding for this provider — don't block; let the real CLI
    # surface its own "no credentials" error (more specific than ours).
    [[ -z "$id" ]] && return 0
    # Let stderr through so the user sees the Ping/API/Chat table (that's
    # real feedback, not noise) — a silent 1-2s pause before claude looks
    # like the shell hanging. Stdin still redirected from /dev/null so any
    # interactive prompt from aikey test (shouldn't happen post plan D,
    # belt-and-suspenders against a regression) can't block the wrapper.
    # Bring proxy up first. Why here (not in the wrapper above): when
    # ensure-running fails (binary missing, port conflict, wrong password),
    # we want to SKIP the test call — otherwise `aikey test` prints its
    # own "aikey-proxy is not running. Run `aikey proxy start` and retry."
    # message, which is misleading (the system already tried). Skipping
    # the test means the user sees only ensure-running's own error, then
    # the "Continue anyway?" prompt below with a clear "could not be
    # started" reason. Warm-start (proxy already up) is a silent ~20ms
    # TCP probe — invisible to humans.
    command aikey proxy ensure-running </dev/null
    local rc=$?
    if [[ $rc -eq 0 ]]; then
        command aikey test "$id" </dev/null
        rc=$?
    fi
    [[ $rc -eq 0 ]] && return 0
    # Exit codes from `aikey test` (see main.rs Commands::Test):
    #   1 = Ping(PROXY) fail · 2 = API fail · 3 = alias not found
    #   5 = aikey-proxy could not be started (from either ensure-running
    #       or test's own check) · other = unexpected
    local reason
    case "$rc" in
        1) reason="proxy can't reach upstream" ;;
        2) reason="API rejected the key" ;;
        3) reason="alias not found" ;;
        5) reason="aikey-proxy could not be started" ;;
        *) reason="exit=$rc" ;;
    esac
    printf '\033[33m[aikey] preflight failed for %s (%s): %s. Continue anyway? [y/N] \033[0m' "$prov" "$id" "$reason"
    local reply
    read -r reply
    case "$reply" in
        y|Y|yes|YES) return 0 ;;
        *) printf '\033[90m[aikey] aborted — run: aikey test %s\033[0m\n' "$id"; return 1 ;;
    esac
}

# Clear-before-handoff for terminals with broken alt-screen (2026-04-27).
#
# Symptom: when preflight runs `aikey test`, several lines hit the main
# screen. The wrapped command (claude / codex) then enters its own TUI
# via `\x1b[?1049h`. On terminals that DON'T implement alt-screen as a
# separate buffer (older macOS Terminal.app, some VTE forks) the
# preflight output gets "snapshotted" into the alt-screen entry and
# ghosts under the wrapped TUI's own rendering — users report seeing
# multiple stacked window snapshots.
#
# Heuristic mirrors `terminal_supports_alt_screen` in
# aikey-cli/src/commands_watch.rs. Modern emulators (iTerm.app,
# WezTerm, Kitty, vscode, Hyper, GNOME Terminal, modern Terminal.app)
# handle alt-screen properly → keep preflight output visible. Known-
# broken terminals → clear before handoff so the wrapped TUI starts
# on a blank canvas.
#
# Override knobs:
#   AIKEY_PREFLIGHT_NO_CLEAR=1     → never clear
#   AIKEY_PREFLIGHT_FORCE_CLEAR=1  → always clear (for false negatives)
_aikey_clear_before_tui_handoff() {
    [[ "$AIKEY_PREFLIGHT_NO_CLEAR" == "1" ]] && return 0
    if [[ "$AIKEY_PREFLIGHT_FORCE_CLEAR" == "1" ]]; then
        printf '\033[H\033[2J' >&2
        return 0
    fi
    # Non-interactive (stderr not a TTY) — no human to confuse.
    [[ ! -t 2 ]] && return 0
    # Multiplexer pass-through: tmux / screen handle alt-screen safely.
    [[ -n "$TMUX" ]] && return 0
    [[ -n "$STY"  ]] && return 0
    case "$TERM" in
        screen*|tmux*) return 0 ;;
        dumb|unknown|"") printf '\033[H\033[2J' >&2; return 0 ;;
    esac
    # Old macOS Terminal.app (build < 433) is the canonical broken case.
    if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]]; then
        local build="${TERM_PROGRAM_VERSION:-0}"
        # Strip any decoration (rare, but defensive: parse only digits).
        build="${build//[^0-9]/}"
        [[ -z "$build" ]] && build=0
        if (( build < 433 )); then
            printf '\033[H\033[2J' >&2
        fi
        return 0
    fi
    # Modern terminals: trust them, leave preflight output visible.
    return 0
}

# Wrap claude + codex. Guarded so the user's own function/alias (if any)
# wins — respects the same convention as the `ak` wrapper above.
# claude / codex: `_aikey_preflight` runs `aikey test`, which now itself
# auto-starts aikey-proxy if it's down (via the same env-var/cache/TTY-prompt
# chain `aikey use` uses). So the wrapper has nothing extra to do — the
# cold-start sequence (password prompt → "proxy started" → connectivity
# table) all happens inside one `aikey test` call.
if ! (( ${+functions[claude]} )) && ! alias claude >/dev/null 2>&1; then
    function claude {
        _aikey_preflight anthropic || return $?
        _aikey_clear_before_tui_handoff
        command claude "$@"
    }
fi
if ! (( ${+functions[codex]} )) && ! alias codex >/dev/null 2>&1; then
    function codex {
        _aikey_preflight openai || return $?
        _aikey_clear_before_tui_handoff
        command codex "$@"
    }
fi
# kimi: auto-start proxy ONLY — NO diagnostic preflight.
# Why scoped this narrowly: the 2026-04-22 carve-out kept kimi out of
# `_aikey_preflight` because `aikey test` historically false-positived on
# kimi's coding-API (subscription / coding-tier model 404). The carve-out
# is pinned by `hook_preflight_does_not_shadow_kimi`. We still want kimi
# users' first invocation to bring the proxy up (parallel to claude/codex)
# so they don't hit a 30-second-in "no proxy" error — `aikey proxy
# ensure-running` is the minimal surface that achieves that without
# re-introducing the false-positive risk. Bugfix:
# workflow/CI/bugfix/2026-04-22-connectivity-probe-through-proxy.md.
if ! (( ${+functions[kimi]} )) && ! alias kimi >/dev/null 2>&1; then
    function kimi {
        command aikey proxy ensure-running </dev/null
        _aikey_clear_before_tui_handoff
        command kimi "$@"
    }
fi


