# ~/.aikey/hook.ps1 — auto-generated by `aikey use`, do not hand-edit
# Version: 4 (PowerShell parity with hook.bash / hook.zsh — Stage 3 windows-compat)

# Stage 3 windows-compat hook design
# ===================================
#
# Mirrors the bash/zsh hooks' contract:
#   - aikey() wrapper: routes activate/deactivate through `aikey ... --shell powershell`,
#     then Invoke-Expression the output (output uses single-quoted strings via
#     `powershell_escape` in src/main.rs — variable expansion / sub-expression
#     are inert, so Invoke-Expression is safe; this is the same security
#     argument bash's `eval` rests on for its single-quoted output).
#   - ak short-alias guarded against pre-existing user definitions.
#   - prompt-wrap precmd: cross-shell sync via active.env.flat (KEY=VALUE only,
#     no eval), gated by AIKEY_AUTO_REFRESH / _AIKEY_EXPLICIT_ALIAS / SEQ diff.
#   - Two-layer drift detector: layer 1 (every prompt, disk hash vs in-memory)
#     + layer 2 (once per session, binary hash vs disk hash).

# Resolve the real aikey.exe binary, bypassing this very wrapper function.
# Why Get-Command + Application: avoids infinite recursion when a user types
# `aikey ...` (which would call our function again instead of the binary).
function global:aikey_resolve_bin {
    $cmd = Get-Command aikey -CommandType Application -ErrorAction SilentlyContinue |
           Select-Object -First 1
    if ($null -eq $cmd) { return $null }
    return $cmd.Source
}

function global:aikey {
    [CmdletBinding()]
    param([Parameter(ValueFromRemainingArguments = $true)] $RemArgs)

    # Defensive: $RemArgs is $null when caller types `aikey` with no args.
    # `@()` coerces both null and a single arg to a real array so .Count
    # / [0] indexing don't trip on PowerShell 5.1 strict-mode-ish hosts.
    $RemArgs = @($RemArgs)

    $bin = aikey_resolve_bin
    if ($null -eq $bin) {
        Write-Error "aikey binary not found on PATH"
        return
    }

    if ($RemArgs.Count -ge 1 -and ($RemArgs[0] -eq 'activate' -or $RemArgs[0] -eq 'deactivate')) {
        # Capture the binary's PowerShell-flavoured output and Invoke-Expression
        # in this session so $env:* assignments + global function defs land in
        # the user's shell. Output is single-quote-escaped (see powershell_escape
        # in src/main.rs) so $vars and $(cmds) inside the captured string are
        # inert — the eval is safe.
        $extra = @($RemArgs) + @('--shell', 'powershell')
        $output = & $bin @extra
        # NB: do NOT `return $LASTEXITCODE`. PowerShell would print the int to
        # the user's stdout (PS functions return values via the output stream,
        # not as exit codes — `0` would appear after every `aikey activate`).
        # The binary already set $LASTEXITCODE; callers who care can check it.
        if ($LASTEXITCODE -eq 0 -and $output) {
            Invoke-Expression ($output -join "`n")
        }
        return
    }

    & $bin @RemArgs
}

# Guarded short-alias. Only define `ak` when the user hasn't already taken
# the name (kubectl shortcut, aws, etc.). Get-Command checks both functions
# and aliases; if either exists, defer.
if (-not (Get-Command ak -ErrorAction SilentlyContinue)) {
    function global:ak {
        [CmdletBinding()]
        param([Parameter(ValueFromRemainingArguments = $true)] $RemArgs)
        aikey @RemArgs
    }
}

# Cross-shell sync (mirrors hook.bash aikey_precmd_bash):
#   - Skip if AIKEY_AUTO_REFRESH=off (kill switch).
#   - Skip if this shell is pinned (_AIKEY_EXPLICIT_ALIAS / AIKEY_ACTIVE_LABEL set
#     by a previous `aikey activate <alias>` in this very session).
#   - Otherwise, read active.env.flat seq and re-import vars only when seq
#     differs from the in-shell value.
#
# Reads active.env.flat (plain KEY=VALUE) instead of active.env (sh syntax)
# because PowerShell can't parse `${NO_PROXY:-}` / `export ...`. The .flat
# variant is written by the same code path as active.env (see
# `write_active_env` in src/commands_account/shell_integration.rs).
function global:aikey_precmd_powershell {
    if ($env:AIKEY_AUTO_REFRESH -eq 'off') { aikey_hook_check_once; return }
    if ($env:_AIKEY_EXPLICIT_ALIAS -or $env:AIKEY_ACTIVE_LABEL) {
        aikey_hook_check_once
        return
    }

    $home_dir = if ($env:HOME) { $env:HOME } else { $env:USERPROFILE }
    if (-not $home_dir) { aikey_hook_check_once; return }
    $flat = Join-Path (Join-Path $home_dir '.aikey') 'active.env.flat'
    if (-not (Test-Path -LiteralPath $flat)) { aikey_hook_check_once; return }

    # Cheap seq probe: read the whole file (small — ~10 KEY=VALUE pairs).
    #
    # Why ReadAllLines (not ReadLines): ReadLines returns an IEnumerable
    # backed by a StreamReader that keeps the file handle open until the
    # enumerator is fully drained or disposed. PowerShell's `foreach` +
    # early `break` does NOT eagerly dispose the enumerator — the handle
    # leaks until the next GC pass (often the entire prompt cycle).
    #
    # The next `aikey use` then can't atomically replace active.env.flat
    # because Windows MoveFileEx returns ERROR_ACCESS_DENIED (os err 5)
    # when the target is held without FILE_SHARE_DELETE (PS opens with
    # only FILE_SHARE_READ | FILE_SHARE_WRITE). Cascade: stale .flat →
    # SEQ matches in-shell → no reload → claude.exe sees no $env:ANTHROPIC_*
    # → user gets login prompt despite a valid binding.
    #
    # ReadAllLines reads the whole file into a string[] and closes the
    # StreamReader synchronously — safe for the small .flat file.
    # See bugfix doc 2026-04-29-active-env-flat-rename-access-denied-on-windows.md.
    $on_disk_seq = $null
    try {
        $flat_lines = [System.IO.File]::ReadAllLines($flat)
        foreach ($line in $flat_lines) {
            if ($line -match '^AIKEY_ACTIVE_SEQ=(\d+)') {
                $on_disk_seq = $Matches[1]
                break
            }
        }
    } catch { aikey_hook_check_once; return }

    # Decide whether to re-import:
    #   - on_disk_seq present + differs from in-shell → reload (cheap path)
    #   - on_disk_seq missing → unconditional reload (mirrors hook.bash's
    #     "Fallback for active.env produced by pre-Stage-1 CLI / by paths
    #     that don't write SEQ"; see commands_account/shell_integration.rs
    #     `write_active_env` which builds a kv_pairs list without SEQ).
    #     Without this fallback, PowerShell users running `aikey use` would
    #     never see the cross-shell sync trigger because .flat from that
    #     code path lacks the SEQ field.
    $in_shell_seq = if ($env:AIKEY_ACTIVE_SEQ) { $env:AIKEY_ACTIVE_SEQ } else { '0' }
    $should_reload = if ($null -eq $on_disk_seq) { $true }
                     else { $on_disk_seq -ne $in_shell_seq }
    if ($should_reload) {
        try {
            # ReadAllLines (not ReadLines) — same handle-leak rationale as
            # the seq-probe above. Even without an early `break`, ReadLines'
            # disposal timing isn't guaranteed across PS hosts, so we
            # standardise on the eager-read pattern throughout this file.
            foreach ($line in [System.IO.File]::ReadAllLines($flat)) {
                if ($line -match '^([^=]+)=(.*)$') {
                    [Environment]::SetEnvironmentVariable($Matches[1], $Matches[2], 'Process')
                }
            }
            if ($env:AIKEY_REFRESH_NOTIFY) {
                $shown_seq = if ($env:AIKEY_ACTIVE_SEQ) { $env:AIKEY_ACTIVE_SEQ } else { 'no-seq' }
                Write-Host ("[aikey] active key refreshed (seq={0})" -f $shown_seq) -ForegroundColor DarkGray
            }
        } catch {
            Write-Host "[aikey] failed to reload active.env.flat: $_" -ForegroundColor Yellow
        }
    }

    aikey_hook_check_once
}

# Two-layer drift detector — mirrors aikey_hook_check_once in hook.bash.
# Layer 1: cheap (every prompt) — disk hook header hash vs in-memory hash.
# Layer 2: spawn `aikey _hook-hash powershell` once per session, compare to disk.
function global:aikey_hook_check_once {
    $home_dir = if ($env:HOME) { $env:HOME } else { $env:USERPROFILE }
    if (-not $home_dir) { return }
    $hook_path = Join-Path (Join-Path $home_dir '.aikey') 'hook.ps1'

    # ── Layer 1 ───────────────────────────────────────────────────────────
    if ($script:_aikey_hook_loaded_hash) {
        $disk_hash = $null
        try {
            # ReadAllLines (not ReadLines) — see seq-probe rationale above.
            # Hook-Template-Hash is on line ~3, so reading the whole file
            # is cheap and avoids the leaked-StreamReader handle problem.
            foreach ($line in [System.IO.File]::ReadAllLines($hook_path)) {
                if ($line -match '^# Hook-Template-Hash:\s+([a-f0-9]+)') {
                    $disk_hash = $Matches[1]
                    break
                }
            }
        } catch { return }
        if ($disk_hash -and $disk_hash -ne $script:_aikey_hook_loaded_hash) {
            $old = $script:_aikey_hook_loaded_hash
            try { . $hook_path } catch {
                Write-Host "[aikey] hook drift detected but auto-reload failed.`n    run manually: . $hook_path" -ForegroundColor Yellow
                return
            }
            if ($script:_aikey_hook_loaded_hash -eq $disk_hash) {
                Write-Host ("[aikey] hook reloaded in this shell ({0} -> {1})" -f $old, $disk_hash) -ForegroundColor DarkGray
                $script:_aikey_hook_layer2_checked = $false
            }
            return
        }
    }

    # ── Layer 2 ───────────────────────────────────────────────────────────
    if ($script:_aikey_hook_layer2_checked) { return }
    $script:_aikey_hook_layer2_checked = $true
    $bin = aikey_resolve_bin
    if ($null -eq $bin) { return }

    $file_hash = $null
    try {
        # ReadAllLines — see seq-probe rationale above.
        foreach ($line in [System.IO.File]::ReadAllLines($hook_path)) {
            if ($line -match '^# Hook-Template-Hash:\s+([a-f0-9]+)') {
                $file_hash = $Matches[1]
                break
            }
        }
    } catch { return }
    $bin_hash = $null
    try { $bin_hash = (& $bin _hook-hash powershell 2>$null).Trim() } catch { return }
    if (-not $file_hash -or -not $bin_hash) { return }

    if ($file_hash -ne $bin_hash) {
        Write-Host ("[aikey] hook.ps1 is outdated (file={0}, binary={1}).`n    run: aikey hook update" -f $file_hash, $bin_hash) -ForegroundColor Yellow
    }
}

# Wrap the prompt function so aikey_precmd_powershell runs before each new
# prompt. Capture the user's existing prompt as a ScriptBlock once (don't
# recapture on subsequent sources — that would nest our own wrapper).
#
# Defensive: `function:prompt` may not exist on stripped hosts (some IDE
# embedded runspaces, scripted automation). `-ErrorAction SilentlyContinue`
# converts the missing-item error into $null; we then fall back to the
# PowerShell default prompt ("PS C:\path> ").
if (-not (Get-Variable -Scope Global -Name _aikeyOrigPromptForHook -ErrorAction SilentlyContinue)) {
    $_aikey_existing_prompt = Get-Item function:prompt -ErrorAction SilentlyContinue
    $_aikey_orig = if ($null -ne $_aikey_existing_prompt) {
        $_aikey_existing_prompt.ScriptBlock
    } else {
        # Default PowerShell prompt — matches what `Microsoft.PowerShell.Core`
        # ships with when no `prompt` function is defined.
        { "PS " + (Get-Location).Path + "> " }
    }
    Set-Variable -Scope Global -Name _aikeyOrigPromptForHook -Value $_aikey_orig
    Remove-Variable -Name _aikey_existing_prompt, _aikey_orig -ErrorAction SilentlyContinue
}
function global:prompt {
    aikey_precmd_powershell
    if ($env:_AIKEY_PROMPT_LABEL) {
        "($env:_AIKEY_PROMPT_LABEL) " + (& $global:_aikeyOrigPromptForHook)
    } else {
        & $global:_aikeyOrigPromptForHook
    }
}

# ── Wrapper preflight (claude / codex) ────────────────────────────────────
#
# Mirror of hook.bash's `aikey_preflight` + `aikey_clear_before_tui_handoff`
# + claude/codex/kimi function wrappers. Same contract:
#
#   - $env:AIKEY_PREFLIGHT = 'off' disables the connectivity probe entirely.
#   - If no active binding ($env:AIKEY_ACTIVE_KEYS empty) → emit advisory
#     line and pass through to the real binary (the user explicitly opted
#     out by not running `aikey use <alias>` first).
#   - Otherwise: `aikey proxy ensure-running` (auto-start proxy if down),
#     then `aikey test <id>` (probe upstream / API / chat).
#   - On non-zero exit: print reason + prompt y/N to continue. Default N.
#
# Why this matters on Windows specifically: PowerShell users running
# `claude`, `codex`, `kimi` against a misconfigured proxy or expired
# credential would otherwise see opaque LLM-side errors. The preflight
# surfaces "API rejected the key" / "proxy can't reach upstream" with a
# concrete next step BEFORE the user's prompt reaches the wrapped CLI.

function global:aikey_preflight {
    [CmdletBinding()]
    param([Parameter(Mandatory)] [string]$Provider)

    if ($env:AIKEY_PREFLIGHT -eq 'off') { return 0 }

    if (-not $env:AIKEY_ACTIVE_KEYS) {
        Write-Host "[aikey] no active binding — run `aikey use <alias>` first (preflight skipped)" `
            -ForegroundColor DarkGray
        return 0
    }

    # AIKEY_ACTIVE_KEYS is a comma-separated provider=virtual_key_id list.
    # Find the entry matching the requested provider.
    $entry = ($env:AIKEY_ACTIVE_KEYS -split ',') |
             Where-Object { $_ -like "${Provider}=*" } |
             Select-Object -First 1
    if (-not $entry) { return 0 }
    $id = ($entry -split '=', 2)[1]
    if (-not $id) { return 0 }

    $bin = aikey_resolve_bin
    if ($null -eq $bin) {
        Write-Host "[aikey] preflight skipped — aikey.exe not on PATH" -ForegroundColor Yellow
        return 0
    }

    # Ensure proxy is up. `aikey proxy ensure-running` is idempotent —
    # cheap noop when proxy is already healthy, ~1-2s when it has to
    # start one. stdin redirected to NUL so a cache-miss password
    # prompt becomes a non-zero exit instead of a hanging wrapper.
    & cmd.exe /c "`"$bin`" proxy ensure-running < NUL > NUL 2>&1"
    $rc = $LASTEXITCODE
    if ($rc -eq 0) {
        # Connectivity probe — full Ping/API/Chat table goes to stderr
        # (visible to user) so a slow probe doesn't look like a hang.
        & $bin test $id
        $rc = $LASTEXITCODE
    }
    if ($rc -eq 0) { return 0 }

    $reason = switch ($rc) {
        1 { 'proxy can`t reach upstream' }
        2 { 'API rejected the key' }
        3 { 'alias not found' }
        5 { 'aikey-proxy could not be started' }
        default { "exit=$rc" }
    }
    Write-Host -NoNewline ("[aikey] preflight failed for {0} ({1}): {2}. Continue anyway? [y/N] " `
        -f $Provider, $id, $reason) -ForegroundColor Yellow
    $reply = Read-Host
    if ($reply -match '^[Yy]') { return 0 }
    return $rc
}

# Some terminals (notably old Apple_Terminal builds) leave residual
# rendering artefacts when an interactive TUI starts. The macOS hook
# has carve-outs for this; on Windows Terminal / cmd / PS host the
# issue doesn't reproduce — keep the function as a no-op for now so
# the wrapper signature stays parallel to bash, but skip the actual
# clear unless explicitly asked via $env:AIKEY_PREFLIGHT_FORCE_CLEAR='1'.
function global:aikey_clear_before_tui_handoff {
    if ($env:AIKEY_PREFLIGHT_NO_CLEAR -eq '1') { return }
    if ($env:AIKEY_PREFLIGHT_FORCE_CLEAR -eq '1') {
        # ESC[H ESC[2J — same VT escape the bash hook uses.
        [Console]::Error.Write("`e[H`e[2J")
    }
    # Default no-op on Windows.
}

# Wrap claude + codex + kimi. Guarded: only define the function if the
# user doesn't already have a function/alias by the same name. We
# deliberately don't check $PATH — that's the binary we'll dispatch to
# via Get-Command -CommandType Application below.
#
# Why Get-Command's -CommandType filter: it lets us check for Function
# / Alias separately from Application. We only skip when a non-binary
# definition exists; the binary on PATH is what we're wrapping.

if (-not (Get-Command claude -CommandType Function, Alias -ErrorAction SilentlyContinue)) {
    function global:claude {
        [CmdletBinding()]
        param([Parameter(ValueFromRemainingArguments = $true)] $RemArgs)
        $RemArgs = @($RemArgs)
        $rc = aikey_preflight -Provider 'anthropic'
        if ($rc -ne 0) { return }
        aikey_clear_before_tui_handoff
        $real = (Get-Command claude -CommandType Application -ErrorAction SilentlyContinue |
                 Select-Object -First 1).Source
        if ($null -eq $real) {
            Write-Error "claude binary not found on PATH"
            return
        }
        & $real @RemArgs
    }
}

if (-not (Get-Command codex -CommandType Function, Alias -ErrorAction SilentlyContinue)) {
    function global:codex {
        [CmdletBinding()]
        param([Parameter(ValueFromRemainingArguments = $true)] $RemArgs)
        $RemArgs = @($RemArgs)
        $rc = aikey_preflight -Provider 'openai'
        if ($rc -ne 0) { return }
        aikey_clear_before_tui_handoff
        $real = (Get-Command codex -CommandType Application -ErrorAction SilentlyContinue |
                 Select-Object -First 1).Source
        if ($null -eq $real) {
            Write-Error "codex binary not found on PATH"
            return
        }
        # `-c model_provider=aikey` overrides the toml top-level model_provider
        # at runtime — see bugfix 2026-05-05 and matching block in hook.zsh.
        & $real -c model_provider=aikey @RemArgs
    }
}

# kimi: auto-start proxy ONLY — NO diagnostic preflight (matches hook.bash
# 2026-04-22 carve-out: kimi-cli has its own connectivity / model probe
# that overlaps with our `aikey test`, doubling the wait every launch).
if (-not (Get-Command kimi -CommandType Function, Alias -ErrorAction SilentlyContinue)) {
    function global:kimi {
        [CmdletBinding()]
        param([Parameter(ValueFromRemainingArguments = $true)] $RemArgs)
        $RemArgs = @($RemArgs)
        $bin = aikey_resolve_bin
        if ($null -ne $bin) {
            & cmd.exe /c "`"$bin`" proxy ensure-running < NUL > NUL 2>&1"
        }
        aikey_clear_before_tui_handoff
        $real = (Get-Command kimi -CommandType Application -ErrorAction SilentlyContinue |
                 Select-Object -First 1).Source
        if ($null -eq $real) {
            Write-Error "kimi binary not found on PATH"
            return
        }
        & $real @RemArgs
    }
}
